

package:
  name: gcc-arm-none-eabi
  version: '10_2020_q4_major'

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 # [linux64]
  md5: 8312c4c91799885f222f663fc81f9a31 # [linux64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-aarch64-linux.tar.bz2 # [aarch64]
  md5: 1c3b8944c026d50362eef1f01f329a8e # [aarch64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-mac.tar.bz2 # [osx]
  md5: e588d21be5a0cc9caa60938d2422b058 # [osx]

build:
  string: '0'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/open-source-software/developer-tools/gnu-toolchain
  license: GPL
  summary: GNU Arm Embedded Toolchain